---
- name: "Copy artifact to backend server"
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: "extract the zipped artifact"
  unarchive:
    src: /home/ubuntu/artifact.tar.gz
    dest: /home/ubuntu/
    remote_src: true

- name: "extract the zipped artifact"
  command: chdir=/home/ubuntu/ {{ item }}
  with_items:
   - npm install
   - pm2 stop default
   - pm2 start npm -- start